### ISSUE TITLE
correct pip install  syntax

### ISSUE THREAD

**Issue by sandipde** [cosmo-epfl/scikit-cosmo#108]
with pip install from github for me had to be 
pip install https://github.com/cosmo-epfl/scikit-cosmo/archive/refs/heads/main.zip
 
the one mentioned in the readme does not work

pip install https://github.com/cosmo-epfl/scikit-cosmo
Collecting https://github.com/cosmo-epfl/scikit-cosmo
  Downloading https://github.com/cosmo-epfl/scikit-cosmo
     - 180 kB 11.9 MB/s
  ERROR: Cannot unpack file /tmp/pip-unpack-wv9lqln4/scikit-cosmo (downloaded from /tmp/pip-req-build-jcs6rwpu, content-type: text/html; charset=utf-8); cannot detect archive format
ERROR: Cannot determine archive format of /tmp/pip-req-build-jcs6rwpu

**Comment by Luthaf** [comment]
Does `pip install git+https://github.com/cosmo-epfl/scikit-cosmo` works for you? That should be the correct command.

**Comment by sandipde** [comment]
yes pip install git+https://github.com/cosmo-epfl/scikit-cosmo works

**Comment by Luthaf** [comment]
Good to know, that's now the updated installation method in the README!
