### ISSUE TITLE
Missing Documentation for Reconstruction Measures

### ISSUE THREAD

**Issue by rosecers** [cosmo-epfl/scikit-cosmo#48]
@agoscinski there needs to be a readthedocs page for the models included in #9 that is well-documented and included in the sphinx toctree.

**Comment by agoscinski** [comment]
can you be a bit more specific? There is a autoclass in the doc in the API reference and I can see the documentation.

**Comment by rosecers** [comment]
The models should have their own landing pages that group them into categories, so that they show up on the left sidebar and in the table of contents. One for `datasets`, one for `model_selection`, one for `metrics`, and one for `linear_model`.
