### ISSUE TITLE
Folder and file naming convention

### ISSUE THREAD

**Issue by agoscinski** [cosmo-epfl/scikit-cosmo#49]
To be closer to the naming convention of sklearn some propositions how to change the naming:

subpackage naming
- pcovr -> decomposition
- selection -> feature_selection

filename convention in subpackages:
- filename.py -> _filename.py (this is not that important I guess)
- base classes of a subpackage to a `_base.py`

test naming convention:
-  subpackage/test_filename.py (I wouldn't be strict about the class structure, one test class might cover multiple classes)

**Comment by rosecers** [comment]
In general in favor, although issues arise with sample selection.

**Comment by agoscinski** [comment]
decided to move selector to feature_selection and have a wrapper code it selection

**Comment by rosecers** [comment]
Addressed in #94
