### ISSUE TITLE
How to integrate Sparse*Methods* with the sklearn pipeline

### ISSUE THREAD

**Issue by agoscinski** [cosmo-epfl/scikit-cosmo#50]
The `Sparse*Methods*` have two inputs and might not work with the sklearn pipeline. Need to check if it works. If it does not work, the pipeline has to be adapted.

**Comment by rosecers** [comment]
Given our conversations about sparse kernels, would you be okay with this issue being closed? It seems as though the solution will be moot with the nystroem modification.

**Comment by agoscinski** [comment]
Yes
