### ISSUE TITLE
Should we write selection methods in fit / transform fashion?

### ISSUE THREAD

**Issue by rosecers** [cosmo-epfl/scikit-cosmo#51]
Looking through sklearn's selection methods, they do `fit/transform` syntax. I'm somewhat of two minds on this: if we do the same, all transform does is returns X[:, features] or X[samples], which feels pretty useless. I could see renaming `select` to `fit` and moving X and Y out of the constructor (which would probably be wise). @ceriottm, @bhelfrecht, and @hurricane642 would appreciate your input.

**Comment by hurricane642** [comment]
What do you mean by renaming `select` to `fit`? We already have `fit` function, and I think, that their functional is ideal. About `transform`, well,  it's already exist for the `SelectorMixin`, and I don't think that we need to make something special
