### ISSUE TITLE
Setup documentation and deploy it

### ISSUE THREAD

**Issue by Luthaf** [cosmo-epfl/scikit-cosmo#6]
We will need to have documentation available online. I suggest we go with the standard Python tool for documentation, i.e. [sphinx](https://www.sphinx-doc.org/), which can extract and render docstrings.

We will need the following part of documentation

- [ ] Introduction and how to install & use the code
- [ ] Tutorials: i.e how to use the code in simple cases. ~This is currently done in notebooks in kernel-tutorials. We could refer to these notebooks in a way or another for tutorials~ EDIT: kernel-tutorial is different, what we need here are "How To" examples
- [ ] API reference, i.e. how to use the code in details. This will be taken from the docstrings

Regarding deployment, the two main options we have are github pages (the doc would live at `https://cosmo-epfl.github.io/sklearn-cosmo/` by default) or readthedocs (`https://sklearn-cosmo.readthedocs.io/` by default). 

If anyone wants to have a go at setting up the documentation, I'm happy to mentor them. Else I'll do something in the next few weeks.

**Comment by rosecers** [comment]
++ readthedocs, highly prefer that medium to github pages

**Comment by Luthaf** [comment]
There should be no difference in the generated doc between github pages & readthedocs, since both would be based on sphinx. 

Do you have any specific issues with github pages? 

I tend to prefer github pages because I had some issues with readthedoc compilation environment for a C++ based project (not really applicable here, but we still have more control over doc deployment with github pages). The big advantage I can see for readthedocs is the automatic generation of `project.readthedocs.io/latest`/`project.readthedocs.io/v0.1.0`/`project.readthedocs.io/v0.2.0` (i.e. having doc online for multiple version of the project). This can be acheived on github pages but needs a bit more work.
