### ISSUE TITLE
Examples and tutorials in documentation, technical choices

### ISSUE THREAD

**Issue by Luthaf** [cosmo-epfl/scikit-cosmo#7]
Splitting up the discussion from https://github.com/cosmo-epfl/sklearn-cosmo/pull/4#issuecomment-714484737.

We will want to have examples and tutorials associated with this repository available somewhere. The goal of this issue is to discuss where such examples should live and which technological choices we want to make.

The first and most obvious solution is to use jupyter notebooks, because they allow mixing code, explanations and figures in a single, easy to edit document. However they have one main drawback: how can we make sure we don't have the usual issue of having small random changes (changes to python version, `execution_count`, etc.) to spend time reviewing?

I see two options: either we try to maintain the notebook in a "clean" state all the time, for which nbstripout is part of the answer, but not everything (for example it does not remove the "last python version used" field); or we don't care, and ignore these changes when reviewing.

If we are using notebooks for examples, I would actually tend to prefer leaving the output so that just viewing the notebook in github web interface or with binder already show all plots. We would still have to be a bit careful with the notebook size. 

Another alternative is to put the example notebooks in kernel-tutorials (or another repo) instead of this repo. We can still have plain python examples in sklearn-cosmo.

What do you think?

**Comment by rosecers** [comment]
Personally, I don't think examples should go in kernel-tutorials. KT should be purely pedagogic and serve a different purpose than use examples. I like the idea of leaving the outputs of the examples, but more-so making very "light" examples that contain 1-2 use cases. For example, the ones I have for feature selection use the sklearn data, so there's no loading of dataset, and plot very little. Thoughts?

**Comment by ceriottm** [comment]
Perhaps the long-term solution for kernel-tutorials is to have them
integrated in a course taught at EPFL or for a summer school.
I agree they have a pedagogic vocation that does not necessarily belong in
the spirit of examples that are meant to be used as
boilerplate code.
So let's keep examples to this repo, tutorials in the existing
kernel-tutorials repo for the time being.
Michele

**Comment by Luthaf** [comment]
Making a few notes after yesterday's meeting: we can have two kind of examples: 

The first kind is inline "usage" examples, that live inside docstrings, and are tested as part of doctests.

The second kind is more advanced end-to-end or "workflow" examples, that can be either separate files with comments, included in sphinx documentation using [literalinclude](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-literalinclude); or written inside sphinx rst sources. The advantages of the first solution is that we can add such examples to tests to ensure they don't bitrot and fall behind API changes. Such examples files could even be ran as part of documentation generation to create plots & other figures.

**Comment by Luthaf** [comment]
Superseded by #90
