### ISSUE TITLE
Examples notebook contain extraneous TOC

### ISSUE THREAD

**Issue by Luthaf** [cosmo-epfl/scikit-cosmo#79]
See the following pages:

https://scikit-cosmo.readthedocs.io/en/latest/read-only-examples/Selectors%2BPipelines.py.html

https://scikit-cosmo.readthedocs.io/en/latest/read-only-examples/PlotGFRE.html

https://scikit-cosmo.readthedocs.io/en/latest/read-only-examples/PlotLFRE.html

@rosecers is there a way to remove the autogenerated TOC before building the documentation?

**Comment by rosecers** [comment]
Addressed in #92
